name: Security Scan (SCA + IaC)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Instalar Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Gerar SBOM da imagem Juice Shop
        run: syft bkimminich/juice-shop -o json > sbom.json

      - name: Escanear vulnerabilidades (falha em HIGH/CRITICAL)
        run: grype sbom:sbom.json --fail-on high

  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar Kubescape
        run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: Escanear manifesto Kubernetes (falha se compliance < 70%)
        run: |
          export PATH=$PATH:$HOME/.kubescape/bin
          kubescape scan framework nsa juice-shop-deployment.yaml --compliance-threshold 70
